#!/usr/bin/env python3
"""
Repo asset index generator.

Walks every git-tracked file, opens it to capture asset-specific metadata, and
writes a complete inventory to INDEX.md (human-readable) and index.json
(machine-readable). Stdlib only — runs with any python3, no dependencies.

Usage (from repo root):
    python scripts/build_index.py
"""

import csv
import json
import struct
import subprocess
from collections import defaultdict, Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def tracked_files():
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout
    return sorted(p for p in out.splitlines() if p and "__pycache__" not in p)


def human(n):
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return f"{n:.0f} {u}" if u == "B" else f"{n:.1f} {u}"
        n /= 1024


def png_dims(path):
    try:
        with open(path, "rb") as f:
            head = f.read(24)
        if head[:8] == b"\x89PNG\r\n\x1a\n" and head[12:16] == b"IHDR":
            w, h = struct.unpack(">II", head[16:24])
            return f"{w}×{h}px"
    except Exception:
        pass
    return ""


def describe(rel):
    """Return (type, description) for a tracked file, opening it when useful."""
    p = ROOT / rel
    ext = p.suffix.lower().lstrip(".") or "file"
    try:
        size = p.stat().st_size
    except OSError:
        size = 0
    meta = {"path": rel, "type": ext, "size_bytes": size, "size": human(size)}
    name = p.name.lower()

    try:
        if ext == "csv":
            with open(p, encoding="utf-8", errors="replace", newline="") as f:
                rdr = csv.reader(f)
                header = next(rdr, [])
                rows = sum(1 for _ in rdr)
            meta.update(rows=rows, cols=len(header), columns=header[:14])
            meta["desc"] = f"{rows:,} rows × {len(header)} cols — {', '.join(header[:6])}{'…' if len(header) > 6 else ''}"
        elif ext == "ipynb":
            nb = json.loads(p.read_text(encoding="utf-8", errors="replace"))
            cells = nb.get("cells", [])
            outs = sum(1 for c in cells if c.get("outputs"))
            meta.update(cells=len(cells), cells_with_output=outs)
            meta["desc"] = f"notebook — {len(cells)} cells, {outs} with output"
        elif ext in ("png", "jpg", "jpeg", "svg"):
            dims = png_dims(p) if ext == "png" else ""
            grp = {"nflx_": "Netflix", "amz_": "Amazon", "goo_": "Google"}.get(name[:5], "")
            meta["desc"] = f"image {dims}".strip() + (f" · {grp}" if grp else "")
        elif ext == "html":
            txt = p.read_text(encoding="utf-8", errors="replace")
            interactive = "plotly" in txt.lower()
            meta["interactive"] = interactive
            meta["desc"] = ("interactive Plotly dashboard" if interactive else "static page") + f" ({human(size)})"
        elif ext == "py":
            txt = p.read_text(encoding="utf-8", errors="replace")
            doc = ""
            if '"""' in txt:
                doc = txt.split('"""', 2)[1].strip().splitlines()[0] if txt.count('"""') >= 2 else ""
            meta["desc"] = doc or "Python module"
        elif ext == "yml" or ext == "yaml":
            for line in p.read_text(errors="replace").splitlines():
                if line.startswith("name:"):
                    meta["desc"] = "workflow: " + line.split(":", 1)[1].strip()
                    break
            meta.setdefault("desc", "YAML config")
        elif ext == "md":
            for line in p.read_text(errors="replace").splitlines():
                if line.startswith("# "):
                    meta["desc"] = line[2:].strip()
                    break
            meta.setdefault("desc", "Markdown doc")
        elif ext == "json":
            d = json.loads(p.read_text(errors="replace"))
            keys = list(d.keys())[:8] if isinstance(d, dict) else [f"array[{len(d)}]"]
            meta["desc"] = "keys: " + ", ".join(map(str, keys))
        else:
            meta["desc"] = ext.upper() + " file"
    except Exception as e:
        meta["desc"] = f"({ext}, unreadable: {e.__class__.__name__})"
    return meta


def main():
    files = tracked_files()
    items = [describe(f) for f in files]

    # group by directory
    by_dir = defaultdict(list)
    for it in items:
        by_dir[str(Path(it["path"]).parent)].append(it)
    type_counts = Counter(it["type"] for it in items)
    total = sum(it["size_bytes"] for it in items)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    md = [f"# Repository Index\n",
          f"*Auto-generated by `scripts/build_index.py` on {stamp}. Re-run to refresh.*\n",
          f"**{len(items)} tracked assets · {human(total)} total**\n",
          "## Inventory by type\n",
          "| Type | Count |", "|------|------:|"]
    for t, c in type_counts.most_common():
        md.append(f"| `{t}` | {c} |")
    md.append("\n## Assets by folder\n")
    for d in sorted(by_dir):
        rows = by_dir[d]
        label = "`/`" if d == "." else f"`{d}/`"
        md.append(f"### {label}  <sub>({len(rows)} files)</sub>\n")
        md.append("| File | Type | Size | Description |")
        md.append("|------|------|-----:|-------------|")
        for it in sorted(rows, key=lambda x: x["path"]):
            fn = Path(it["path"]).name
            md.append(f"| `{fn}` | {it['type']} | {it['size']} | {it.get('desc','')} |")
        md.append("")

    (ROOT / "INDEX.md").write_text("\n".join(md))
    (ROOT / "index.json").write_text(json.dumps(
        {"generated": stamp, "count": len(items), "total_bytes": total, "assets": items}, indent=2))

    print(f"  ✓ INDEX.md + index.json — {len(items)} assets, {human(total)}, {len(by_dir)} folders")
    print("  types:", dict(type_counts.most_common()))


if __name__ == "__main__":
    main()
